# src/accounts/constants/__init__.py

from .choices import *
from .choices import ACCOUNT_STATUS_CHOICES, GENDER_CHOICES, USER_STATUS

# Explicit imports to avoid issues
from .permissions import *
from .permissions import (
    DEFAULT_ADMIN_PERMISSIONS,
    DEFAULT_PARENT_PERMISSIONS,
    DEFAULT_ROLE_MAPPINGS,
    DEFAULT_ROLES,
    DEFAULT_STUDENT_PERMISSIONS,
    DEFAULT_TEACHER_PERMISSIONS,
    PERMISSION_SCOPES,
    ROLE_HIERARCHY,
    SYSTEM_ROLE_NAMES,
)

__all__ = [
    # From choices
    "GENDER_CHOICES",
    "ACCOUNT_STATUS_CHOICES",
    # From permissions
    "PERMISSION_SCOPES",
    "DEFAULT_ADMIN_PERMISSIONS",
    "DEFAULT_TEACHER_PERMISSIONS",
    "DEFAULT_PARENT_PERMISSIONS",
    "DEFAULT_STUDENT_PERMISSIONS",
    "DEFAULT_ROLES",
    "SYSTEM_ROLE_NAMES",
    "ROLE_HIERARCHY",
    "DEFAULT_ROLE_MAPPINGS",
]
