# src/accounts/constants/__init__.py

from .choices import *
from .permissions import *
from .settings import *

# Explicit imports to avoid issues
from .choices import (
    ACCOUNT_STATUS_CHOICES,
    GENDER_CHOICES,
    USER_STATUS,
    TIMEZONE_CHOICES,
    LANGUAGE_CHOICES,
    NOTIFICATION_TYPES,
    AUDIT_ACTION_CHOICES,
    VERIFICATION_TYPES,
    SESSION_STATUS_CHOICES,
)

from .permissions import (
    DEFAULT_ADMIN_PERMISSIONS,
    DEFAULT_PARENT_PERMISSIONS,
    DEFAULT_ROLE_MAPPINGS,
    DEFAULT_ROLES,
    DEFAULT_STUDENT_PERMISSIONS,
    DEFAULT_TEACHER_PERMISSIONS,
    PERMISSION_SCOPES,
    ROLE_HIERARCHY,
    SYSTEM_ROLE_NAMES,
    # PERMISSION_CATEGORIES,
    # ROLE_COLORS,
)

from .settings import (
    SECURITY_SETTINGS,
    AUTHENTICATION_SETTINGS,
    VERIFICATION_SETTINGS,
    SESSION_SETTINGS,
    ANALYTICS_SETTINGS,
    NOTIFICATION_SETTINGS,
    CACHE_SETTINGS,
)

__all__ = [
    # From choices
    "GENDER_CHOICES",
    "ACCOUNT_STATUS_CHOICES",
    "USER_STATUS",
    "TIMEZONE_CHOICES",
    "LANGUAGE_CHOICES",
    "NOTIFICATION_TYPES",
    "AUDIT_ACTION_CHOICES",
    "VERIFICATION_TYPES",
    "SESSION_STATUS_CHOICES",
    # From permissions
    "PERMISSION_SCOPES",
    "DEFAULT_ADMIN_PERMISSIONS",
    "DEFAULT_TEACHER_PERMISSIONS",
    "DEFAULT_PARENT_PERMISSIONS",
    "DEFAULT_STUDENT_PERMISSIONS",
    "DEFAULT_ROLES",
    "SYSTEM_ROLE_NAMES",
    "ROLE_HIERARCHY",
    "DEFAULT_ROLE_MAPPINGS",
    "PERMISSION_CATEGORIES",
    "ROLE_COLORS",
    # From settings
    "SECURITY_SETTINGS",
    "AUTHENTICATION_SETTINGS",
    "VERIFICATION_SETTINGS",
    "SESSION_SETTINGS",
    "ANALYTICS_SETTINGS",
    "NOTIFICATION_SETTINGS",
    "CACHE_SETTINGS",
]
