# Generated by Django 5.2.1 on 2025-05-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#4e73df', help_text='Color for timetable display', max_length=20),
        ),
    ]
