# Generated by Django 5.2.1 on 2025-05-29 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='teachers.teacher', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.term', verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academics.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_syllabi', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academics.grade', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_syllabi', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='subjects.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academics.term', verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='subjects.syllabus', verbose_name='Syllabus'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department', 'is_active'], name='subjects_su_departm_ece9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='subjects_su_code_22ddd2_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_elective'], name='subjects_su_is_elec_de2f22_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['teacher', 'academic_year', 'term'], name='subjects_su_teacher_3ee82e_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['class_assigned', 'academic_year', 'term'], name='subjects_su_class_a_e5dcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['subject', 'academic_year', 'term'], name='subjects_su_subject_332264_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('subject', 'class_assigned', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['subject', 'grade', 'academic_year', 'term'], name='subjects_sy_subject_3841b1_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['academic_year', 'term'], name='subjects_sy_academi_25879b_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['completion_percentage'], name='subjects_sy_complet_35034c_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['is_active'], name='subjects_sy_is_acti_1d6b93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('subject', 'grade', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['syllabus', 'is_completed'], name='subjects_to_syllabu_f3440e_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['completion_date'], name='subjects_to_complet_4894f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicprogress',
            unique_together={('syllabus', 'topic_index')},
        ),
    ]
