# Generated by Django 5.2.1 on 2025-05-29 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('scheduling', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='substituteteacher',
            name='substitute_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['day_of_week', 'start_time'], name='scheduling__day_of__e674b7_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['period_number'], name='scheduling__period__d30e51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day_of_week', 'period_number', 'start_time')},
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='scheduling.room'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.term'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduling.timeslot'),
        ),
        migrations.AddField(
            model_name='substituteteacher',
            name='original_timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='scheduling.timetable'),
        ),
        migrations.AddField(
            model_name='timetablegeneration',
            name='grades',
            field=models.ManyToManyField(related_name='timetable_generations', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='timetablegeneration',
            name='started_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetablegeneration',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_generations', to='academics.term'),
        ),
        migrations.AddField(
            model_name='timetabletemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetabletemplate',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='academics.grade'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['class_assigned', 'term'], name='scheduling__class_a_606b28_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher', 'term'], name='scheduling__teacher_3737fe_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['time_slot', 'effective_from_date'], name='scheduling__time_sl_537902_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['is_active'], name='scheduling__is_acti_cca0ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_assigned', 'time_slot', 'effective_from_date', 'effective_to_date'), ('room', 'time_slot', 'effective_from_date', 'effective_to_date'), ('teacher', 'time_slot', 'effective_from_date', 'effective_to_date')},
        ),
        migrations.AddIndex(
            model_name='substituteteacher',
            index=models.Index(fields=['date'], name='scheduling__date_9330e9_idx'),
        ),
        migrations.AddIndex(
            model_name='substituteteacher',
            index=models.Index(fields=['substitute_teacher', 'date'], name='scheduling__substit_9796bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='substituteteacher',
            unique_together={('original_timetable', 'date')},
        ),
    ]
