# Generated by Django 5.2.1 on 2025-05-29 14:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='marked at')),
                ('remarks', models.TextField(blank=True, verbose_name='remarks')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.class', verbose_name='class')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL, verbose_name='marked by')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ['-date'],
                'unique_together': {('class_obj', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10, verbose_name='status')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='attendance.attendancerecord', verbose_name='attendance record')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student attendance',
                'verbose_name_plural': 'student attendances',
                'unique_together': {('attendance_record', 'student')},
            },
        ),
    ]
