# Generated by Django 5.2.1 on 2025-05-19 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="courses.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="marked by",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="attendance_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendances",
                to="attendance.attendancerecord",
                verbose_name="attendance record",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="students.student",
                verbose_name="student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("class_obj", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("attendance_record", "student")},
        ),
    ]
