# Generated by Django 5.2.1 on 2025-05-19 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Is Recurring"),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Fee Category",
                "verbose_name_plural": "Fee Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_category",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("supplies", "Supplies"),
                            ("transport", "Transport"),
                            ("events", "Events"),
                            ("miscellaneous", "Miscellaneous"),
                        ],
                        max_length=20,
                        verbose_name="Expense Category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Expense Date"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                ("paid_to", models.CharField(max_length=100, verbose_name="Paid To")),
                (
                    "receipt_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expense_receipts/",
                        verbose_name="Receipt Attachment",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "due_day_of_month",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Day of month when fee is due",
                        verbose_name="Due Day of Month",
                    ),
                ),
                (
                    "late_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of fee charged as late fee",
                        max_digits=5,
                        verbose_name="Late Fee Percentage",
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of days after due date before late fee applies",
                        verbose_name="Grace Period (Days)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="courses.academicyear",
                        verbose_name="Academic Year",
                    ),
                ),
                (
                    "fee_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="finance.feecategory",
                        verbose_name="Fee Category",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="courses.grade",
                        verbose_name="Grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Structure",
                "verbose_name_plural": "Fee Structures",
                "ordering": ["academic_year", "grade", "fee_category"],
                "unique_together": {("academic_year", "grade", "fee_category")},
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Invoice Number"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Issue Date"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Amount"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Net Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="courses.academicyear",
                        verbose_name="Academic Year",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Net Amount"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "fee_structure",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="finance.feestructure",
                        verbose_name="Fee Structure",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Payment Date"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("cheque", "Cheque"),
                            ("online", "Online Payment"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Receipt Number"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="finance.invoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Received By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=20,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Discount Value"
                    ),
                ),
                (
                    "criteria",
                    models.CharField(
                        choices=[
                            ("merit", "Merit Based"),
                            ("need", "Need Based"),
                            ("sports", "Sports Quota"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Criteria",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to="courses.academicyear",
                        verbose_name="Academic Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scholarship",
                "verbose_name_plural": "Scholarships",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentScholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Approval Date"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="approved",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_scholarships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_scholarships",
                        to="finance.scholarship",
                        verbose_name="Scholarship",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Scholarship",
                "verbose_name_plural": "Student Scholarships",
                "ordering": ["-approval_date"],
            },
        ),
    ]
