from django.contrib.auth.decorators import login_required
from django.urls import include, path

from . import views

app_name = "finance"

urlpatterns = [
    # API URLs
    path("api/", include("finance.api.urls")),
    # Web interface URLs (for future HTML templates)
    path("", login_required(views.DashboardView.as_view()), name="dashboard"),
    # Fee Management
    path(
        "fee-categories/",
        login_required(views.FeeCategoryListView.as_view()),
        name="fee-category-list",
    ),
    path(
        "fee-categories/create/",
        login_required(views.FeeCategoryCreateView.as_view()),
        name="fee-category-create",
    ),
    path(
        "fee-categories/<int:pk>/",
        login_required(views.FeeCategoryDetailView.as_view()),
        name="fee-category-detail",
    ),
    path(
        "fee-categories/<int:pk>/edit/",
        login_required(views.FeeCategoryUpdateView.as_view()),
        name="fee-category-edit",
    ),
    path(
        "fee-structures/",
        login_required(views.FeeStructureListView.as_view()),
        name="fee-structure-list",
    ),
    path(
        "fee-structures/create/",
        login_required(views.FeeStructureCreateView.as_view()),
        name="fee-structure-create",
    ),
    path(
        "fee-structures/<int:pk>/",
        login_required(views.FeeStructureDetailView.as_view()),
        name="fee-structure-detail",
    ),
    path(
        "fee-structures/<int:pk>/edit/",
        login_required(views.FeeStructureUpdateView.as_view()),
        name="fee-structure-edit",
    ),
    path(
        "special-fees/",
        login_required(views.SpecialFeeListView.as_view()),
        name="special-fee-list",
    ),
    path(
        "special-fees/create/",
        login_required(views.SpecialFeeCreateView.as_view()),
        name="special-fee-create",
    ),
    path(
        "special-fees/<int:pk>/",
        login_required(views.SpecialFeeDetailView.as_view()),
        name="special-fee-detail",
    ),
    # Scholarship Management
    path(
        "scholarships/",
        login_required(views.ScholarshipListView.as_view()),
        name="scholarship-list",
    ),
    path(
        "scholarships/create/",
        login_required(views.ScholarshipCreateView.as_view()),
        name="scholarship-create",
    ),
    path(
        "scholarships/<int:pk>/",
        login_required(views.ScholarshipDetailView.as_view()),
        name="scholarship-detail",
    ),
    path(
        "scholarships/<int:pk>/assign/",
        login_required(views.ScholarshipAssignView.as_view()),
        name="scholarship-assign",
    ),
    path(
        "student-scholarships/",
        login_required(views.StudentScholarshipListView.as_view()),
        name="student-scholarship-list",
    ),
    path(
        "student-scholarships/<int:pk>/approve/",
        login_required(views.StudentScholarshipApproveView.as_view()),
        name="student-scholarship-approve",
    ),
    # Invoice Management
    path(
        "invoices/",
        login_required(views.InvoiceListView.as_view()),
        name="invoice-list",
    ),
    path(
        "invoices/generate/",
        login_required(views.InvoiceGenerateView.as_view()),
        name="invoice-generate",
    ),
    path(
        "invoices/bulk-generate/",
        login_required(views.BulkInvoiceGenerateView.as_view()),
        name="bulk-invoice-generate",
    ),
    path(
        "invoices/<int:pk>/",
        login_required(views.InvoiceDetailView.as_view()),
        name="invoice-detail",
    ),
    path(
        "invoices/<int:pk>/pdf/",
        login_required(views.InvoicePDFView.as_view()),
        name="invoice-pdf",
    ),
    # Payment Management
    path(
        "payments/",
        login_required(views.PaymentListView.as_view()),
        name="payment-list",
    ),
    path(
        "payments/process/",
        login_required(views.PaymentProcessView.as_view()),
        name="payment-process",
    ),
    path(
        "payments/<int:pk>/",
        login_required(views.PaymentDetailView.as_view()),
        name="payment-detail",
    ),
    path(
        "payments/<int:pk>/receipt/",
        login_required(views.PaymentReceiptView.as_view()),
        name="payment-receipt",
    ),
    # Fee Waivers
    path(
        "fee-waivers/",
        login_required(views.FeeWaiverListView.as_view()),
        name="fee-waiver-list",
    ),
    path(
        "fee-waivers/create/",
        login_required(views.FeeWaiverCreateView.as_view()),
        name="fee-waiver-create",
    ),
    path(
        "fee-waivers/<int:pk>/",
        login_required(views.FeeWaiverDetailView.as_view()),
        name="fee-waiver-detail",
    ),
    path(
        "fee-waivers/<int:pk>/approve/",
        login_required(views.FeeWaiverApproveView.as_view()),
        name="fee-waiver-approve",
    ),
    # Reports and Analytics
    path("reports/", login_required(views.ReportsView.as_view()), name="reports"),
    path(
        "reports/collection/",
        login_required(views.CollectionReportView.as_view()),
        name="collection-report",
    ),
    path(
        "reports/defaulters/",
        login_required(views.DefaultersReportView.as_view()),
        name="defaulters-report",
    ),
    path(
        "reports/scholarships/",
        login_required(views.ScholarshipReportView.as_view()),
        name="scholarship-report",
    ),
    path(
        "reports/financial-summary/",
        login_required(views.FinancialSummaryReportView.as_view()),
        name="financial-summary-report",
    ),
    path("analytics/", login_required(views.AnalyticsView.as_view()), name="analytics"),
    path(
        "analytics/collection-metrics/",
        login_required(views.CollectionMetricsView.as_view()),
        name="collection-metrics",
    ),
    path(
        "analytics/payment-trends/",
        login_required(views.PaymentTrendsView.as_view()),
        name="payment-trends",
    ),
    # Utility endpoints
    path(
        "calculate-fees/",
        login_required(views.CalculateFeesView.as_view()),
        name="calculate-fees",
    ),
    path(
        "search-students/",
        login_required(views.StudentSearchView.as_view()),
        name="search-students",
    ),
    path(
        "search-invoices/",
        login_required(views.InvoiceSearchView.as_view()),
        name="search-invoices",
    ),
    # AJAX endpoints for dynamic forms
    path(
        "ajax/grades-by-section/",
        views.GradesBySectionView.as_view(),
        name="ajax-grades-by-section",
    ),
    path(
        "ajax/classes-by-grade/",
        views.ClassesByGradeView.as_view(),
        name="ajax-classes-by-grade",
    ),
    path(
        "ajax/students-by-class/",
        views.StudentsByClassView.as_view(),
        name="ajax-students-by-class",
    ),
    path(
        "ajax/invoice-details/",
        views.InvoiceDetailsView.as_view(),
        name="ajax-invoice-details",
    ),
]
