# Generated by Django 5.2.1 on 2025-05-29 17:29

import django.core.validators
import django.db.models.deletion
import src.accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications via email', verbose_name='email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(default='en', help_text="User's preferred language", max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive notifications via SMS', verbose_name='SMS notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_preference',
            field=models.CharField(default='UTC', help_text="User's preferred timezone", max_length=50, verbose_name='timezone'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='session key'),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10, verbose_name='severity'),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=50, verbose_name='education level'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='emergency contact name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='emergency contact phone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='emergency contact relationship'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='employee ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, help_text='Current or most recent educational institution', max_length=200, verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_profile_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='occupation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, verbose_name='profile views'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='color_code',
            field=models.CharField(default='#007bff', help_text='Hex color code for UI display', max_length=7, verbose_name='color code'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Role to inherit permissions from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='accounts.userrole', verbose_name='parent role'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='assignment_reason',
            field=models.CharField(blank=True, help_text='Reason for role assignment', max_length=200, verbose_name='assignment reason'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='requires approval'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='browser',
            field=models.CharField(blank=True, max_length=50, verbose_name='browser'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='device type'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='logout_reason',
            field=models.CharField(blank=True, choices=[('user', 'User Logout'), ('timeout', 'Session Timeout'), ('security', 'Security Logout'), ('admin', 'Admin Logout')], max_length=50, verbose_name='logout reason'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os',
            field=models.CharField(blank=True, max_length=50, verbose_name='operating system'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Must be a valid email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional. Include country code for international numbers.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 2MB, JPEG/PNG only)', null=True, upload_to=src.accounts.models.user_profile_picture_path, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('role_assign', 'Role Assigned'), ('role_remove', 'Role Removed'), ('account_lock', 'Account Locked'), ('account_unlock', 'Account Unlocked'), ('email_verify', 'Email Verified'), ('phone_verify', 'Phone Verified'), ('2fa_enable', '2FA Enabled'), ('2fa_disable', '2FA Disabled'), ('profile_view', 'Profile Viewed'), ('export', 'Data Export'), ('import', 'Data Import')], max_length=20, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified', 'phone_verified'], name='accounts_us_email_v_262863_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='accounts_us_severit_bf052a_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='accounts_us_ip_addr_c78954_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['requires_approval', 'approved_at'], name='accounts_us_require_51dcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address'], name='accounts_us_ip_addr_0fc6b1_idx'),
        ),
    ]
