# Generated by Django 5.2.1 on 2025-07-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional for students. Email address for login and communication.', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
