# Generated by Django 5.2.1 on 2025-05-19 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "setting_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Setting Key"
                    ),
                ),
                ("setting_value", models.TextField(verbose_name="Setting Value")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        max_length=20,
                        verbose_name="Data Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="Is Editable"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "ordering": ["setting_key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view", "View"),
                            ("download", "Download"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=100, verbose_name="Entity Type"),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Entity ID"
                    ),
                ),
                (
                    "data_before",
                    models.JSONField(blank=True, null=True, verbose_name="Data Before"),
                ),
                (
                    "data_after",
                    models.JSONField(blank=True, null=True, verbose_name="Data After"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file_path",
                    models.FileField(upload_to="documents/", verbose_name="File Path"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=50, verbose_name="File Type"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Upload Date"),
                ),
                ("category", models.CharField(max_length=100, verbose_name="Category")),
                (
                    "related_to_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Related To ID",
                    ),
                ),
                (
                    "related_to_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Related To Type",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Is Public"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-upload_date"],
            },
        ),
    ]
