# Generated by Django 5.2.1 on 2025-05-29 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classperformanceanalytics',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='classperformanceanalytics',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='studentperformanceanalytics',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddIndex(
            model_name='systemhealthmetrics',
            index=models.Index(fields=['-timestamp'], name='core_system_timesta_3bf54b_idx'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherperformanceanalytics',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='teacherperformanceanalytics',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='teacherperformanceanalytics',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddIndex(
            model_name='attendanceanalytics',
            index=models.Index(fields=['entity_type', 'entity_id'], name='core_attend_entity__04d429_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceanalytics',
            index=models.Index(fields=['academic_year', 'term'], name='core_attend_academi_91069e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceanalytics',
            index=models.Index(fields=['attendance_percentage'], name='core_attend_attenda_ac7a15_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceanalytics',
            index=models.Index(fields=['calculated_at'], name='core_attend_calcula_5a3efe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceanalytics',
            unique_together={('entity_type', 'entity_id', 'academic_year', 'term', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', '-timestamp'], name='core_auditl_content_cf754b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module_name', '-timestamp'], name='core_auditl_module__ef9e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='classperformanceanalytics',
            index=models.Index(fields=['class_instance', 'academic_year', 'term'], name='core_classp_class_i_08b8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='classperformanceanalytics',
            index=models.Index(fields=['academic_year', 'term', 'subject'], name='core_classp_academi_c577c2_idx'),
        ),
        migrations.AddIndex(
            model_name='classperformanceanalytics',
            index=models.Index(fields=['calculated_at'], name='core_classp_calcula_ee9bc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classperformanceanalytics',
            unique_together={('class_instance', 'academic_year', 'term', 'subject')},
        ),
        migrations.AddIndex(
            model_name='studentperformanceanalytics',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='core_studen_student_9cd0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformanceanalytics',
            index=models.Index(fields=['academic_year', 'term', 'subject'], name='core_studen_academi_f3c974_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformanceanalytics',
            index=models.Index(fields=['calculated_at'], name='core_studen_calcula_3a6b20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentperformanceanalytics',
            unique_together={('student', 'academic_year', 'term', 'subject')},
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['category'], name='core_system_categor_c152a0_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['setting_key'], name='core_system_setting_f7ca3d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherperformanceanalytics',
            index=models.Index(fields=['teacher', 'academic_year', 'term'], name='core_teache_teacher_339a34_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherperformanceanalytics',
            index=models.Index(fields=['academic_year', 'term'], name='core_teache_academi_39cf28_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherperformanceanalytics',
            index=models.Index(fields=['overall_performance_score'], name='core_teache_overall_e0f370_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherperformanceanalytics',
            index=models.Index(fields=['calculated_at'], name='core_teache_calcula_846f73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherperformanceanalytics',
            unique_together={('teacher', 'academic_year', 'term')},
        ),
    ]
