# Generated by Django 5.2.1 on 2025-06-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_financialanalytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialAnalytics',
        ),
    ]
