# Generated by Django 5.2.1 on 2025-05-29 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='additional_supervisors',
            field=models.ManyToManyField(blank=True, related_name='additional_supervised_exams', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.class'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_exams', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examtype'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_systems', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='grading_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='exams.gradingsystem'),
        ),
        migrations.AddField(
            model_name='exam',
            name='grading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.gradingsystem'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='exam_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_exam', to='exams.examschedule'),
        ),
        migrations.AddField(
            model_name='onlineexamquestion',
            name='online_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.onlineexam'),
        ),
        migrations.AddField(
            model_name='onlineexamquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examquestion'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='questions',
            field=models.ManyToManyField(through='exams.OnlineExamQuestion', to='exams.examquestion'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.class'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.term'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='exam_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='exams.examschedule'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.term'),
        ),
        migrations.AddField(
            model_name='studentonlineexamattempt',
            name='online_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='exams.onlineexam'),
        ),
        migrations.AddField(
            model_name='studentonlineexamattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exam_attempts', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('exam', 'class_obj', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='gradingsystem',
            unique_together={('academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('grading_system', 'grade_name')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='onlineexamquestion',
            unique_together={('online_exam', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='studentexamresult',
            unique_together={('student', 'exam_schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='studentonlineexamattempt',
            unique_together={('student', 'online_exam', 'attempt_number')},
        ),
    ]
