# Generated by Django 5.2.1 on 2025-07-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexamresult',
            options={'ordering': ['-percentage', 'student__last_name']},
        ),
    ]
